# Generated by Django 3.2.5 on 2021-07-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boitoi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
