# Generated by Django 3.2.5 on 2021-07-27 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boitoi', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_address', models.CharField(default=' ', max_length=300, null=True)),
                ('stattus', models.CharField(choices=[('Pending', 'Pending'), ('Delevered', 'Delevered'), ('On the way', 'On the Way')], default='Pending', max_length=50, null=True)),
                ('pay_stattus', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=50, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('estimated_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boitoi.customer')),
                ('pay_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boitoi.paymethod')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boitoi.book')),
            ],
        ),
    ]
